# HYPRLOCK - alba4k
#
# Documentation: https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock

# Authentication methods

auth {
    fingerprint {
        enabled = false
        max_retries = 10
        retry_delay = 100
    }
    
    pam {
        enabled = true
        # module = hyprlock
    }
}

